
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_database
    username: postgres
    password: Dotinha2012@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true