
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_database
    username: postgres
    password: Dotinha2012@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: alexandregv1999@gmail.com 
    password: atnnbhmbftqnxgua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
